package main

import ()

// redis all command is 194
/*
	http://redis.io/commands
	$( $(".command") ).each(function( index ) {
	  console.log( '"' + $.trim($( this ).contents().get(0).nodeValue) + '":		{},' );
	  $("body").append('"' + $.trim($( this ).contents().get(0).nodeValue) + '":		{}, <br />' )
	});
*/
// Keep sorted for future command addition
var redisCommands = map[string] bool{
	"APPEND":                        true,
	"AUTH":                          false,
	"BGREWRITEAOF":                  true,
	"BGSAVE":                        true,
	"BITCOUNT":                      false,
	"BITOP":                         true,
	"BITPOS":                        true,
	"BLPOP":                         true,
	"BRPOP":                         true,
	"BRPOPLPUSH":                    true,
	"CLIENT KILL":                   true,
	"CLIENT LIST":                   false,
	"CLIENT GETNAME":                false,
	"CLIENT PAUSE":                  true,
	"CLIENT SETNAME":                true,
	"CLUSTER ADDSLOTS":              true,
	"CLUSTER COUNT-FAILURE-REPORTS": false,
	"CLUSTER COUNTKEYSINSLOT":       false,
	"CLUSTER DELSLOTS":              true,
	"CLUSTER FAILOVER":              true,
	"CLUSTER FORGET":                true,
	"CLUSTER GETKEYSINSLOT":         true,
	"CLUSTER INFO":                  false,
	"CLUSTER KEYSLOT":               false,
	"CLUSTER MEET":                  true,
	"CLUSTER NODES":                 false,
	"CLUSTER REPLICATE":             true,
	"CLUSTER RESET":                 true,
	"CLUSTER SAVECONFIG":            false,
	"CLUSTER SET-CONFIG-EPOCH":      true,
	"CLUSTER SETSLOT":               true,
	"CLUSTER SLAVES":                false,
	"CLUSTER SLOTS":                 false,
	"COMMAND":                       false,
	"COMMAND COUNT":                 false,
	"COMMAND GETKEYS":               false,
	"COMMAND INFO":                  false,
	"CONFIG GET":                    false,
	"CONFIG REWRITE":                true,
	"CONFIG SET":                    true,
	"CONFIG RESETSTAT":              true,
	"DBSIZE":                        false,
	"DEBUG OBJECT":                  false,
	"DEBUG SEGFAULT":                true,
	"DECR":                          true,
	"DECRBY":                        true,
	"DEL":                           true,
	"DISCARD":                       true,
	"DUMP":                          true,
	"ECHO":                          false,
	"EVAL":                          true,
	"EVALSHA":                       true,
	"EXEC":                          true,
	"EXISTS":                        false,
	"EXPIRE":                        true,
	"EXPIREAT":                      true,
	"FLUSHALL":                      true,
	"FLUSHDB":                       true,
	"GEOADD":                        true,
	"GEOHASH":                       false,
	"GEOPOS":                        false,
	"GEODIST":                       false,
	"GEORADIUS":                     false,
	"GEORADIUSBYMEMBER":             false,
	"GET":                           false,
	"GETBIT":                        false,
	"GETRANGE":                      false,
	"GETSET":                        true,
	"HDEL":                          true,
	"HEXISTS":                       false,
	"HGET":                          false,
	"HGETALL":                       false,
	"HINCRBY":                       true,
	"HINCRBYFLOAT":                  true,
	"HKEYS":                         false,
	"HLEN":                          false,
	"HMGET":                         false,
	"HMSET":                         true,
	"HSET":                          true,
	"HSETNX":                        true,
	"HSTRLEN":                       false,
	"HVALS":                         false,
	"INCR":                          true,
	"INCRBY":                        true,
	"INCRBYFLOAT":                   true,
	"INFO":                          false,
	"KEYS":                          false,
	"LASTSAVE":                      false,
	"LINDEX":                        false,
	"LINSERT":                       true,
	"LLEN":                          false,
	"LPOP":                          true,
	"LPUSH":                         true,
	"LPUSHX":                        true,
	"LRANGE":                        false,
	"LREM":                          true,
	"LSET":                          true,
	"LTRIM":                         true,
	"MGET":                          false,
	"MIGRATE":                       true,
	"MONITOR":                       true,
	"MOVE":                          true,
	"MSET":                          true,
	"MSETNX":                        true,
	"MULTI":                         true,
	"OBJECT":                        false,
	"PERSIST":                       true,
	"PEXPIRE":                       true,
	"PEXPIREAT":                     true,
	"PFADD":                         true,
	"PFCOUNT":                       false,
	"PFMERGE":                       true,
	"PING":                          false,
	"PSETEX":                        true,
	"PSUBSCRIBE":                    true,
	"PUBSUB":                        true,
	"PTTL":                          false,
	"PUBLISH":                       true,
	"PUNSUBSCRIBE":                  true,
	"QUIT":                          true,
	"RANDOMKEY":                     true,
	"READONLY":                      true,
	"READWRITE":                     true,
	"RENAME":                        true,
	"RENAMENX":                      true,
	"RESTORE":                       true,
	"ROLE":                          false,
	"RPOP":                          true,
	"RPOPLPUSH":                     true,
	"RPUSH":                         true,
	"RPUSHX":                        true,
	"SADD":                          true,
	"SAVE":                          false,
	"SCARD":                         false,
	"SCRIPT EXISTS":                 false,
	"SCRIPT FLUSH":                  true,
	"SCRIPT KILL":                   true,
	"SCRIPT LOAD":                   true,
	"SDIFF":                         false,
	"SDIFFSTORE":                    false,
	"SELECT":                        true,
	"SET":                           true,
	"SETBIT":                        true,
	"SETEX":                         true,
	"SETNX":                         true,
	"SETRANGE":                      true,
	"SHUTDOWN":                      true,
	"SINTER":                        true,
	"SINTERSTORE":                   true,
	"SISMEMBER":                     false,
	"SLAVEOF":                       true,
	"SLOWLOG":                       true,
	"SMEMBERS":                      false,
	"SMOVE":                         true,
	"SORT":                          true,
	"SPOP":                          true,
	"SRANDMEMBER":                   false,
	"SREM":                          true,
	"STRLEN":                        false,
	"SUBSCRIBE":                     true,
	"SUNION":                        true,
	"SUNIONSTORE":                   true,
	"SYNC":                          true,
	"TIME":                          false,
	"TTL":                           false,
	"TYPE":                          true,
	"UNSUBSCRIBE":                   true,
	"UNWATCH":                       true,
	"WAIT":                          true,
	"WATCH":                         true,
	"ZADD":                          true,
	"ZCARD":                         false,
	"ZCOUNT":                        false,
	"ZINCRBY":                       true,
	"ZINTERSTORE":                   true,
	"ZLEXCOUNT":                     false,
	"ZRANGE":                        false,
	"ZRANGEBYLEX":                   false,
	"ZREVRANGEBYLEX":                false,
	"ZRANGEBYSCORE":                 false,
	"ZRANK":                         false,
	"ZREM":                          true,
	"ZREMRANGEBYLEX":                true,
	"ZREMRANGEBYRANK":               true,
	"ZREMRANGEBYSCORE":              true,
	"ZREVRANGE":                     false,
	"ZREVRANGEBYSCORE":              false,
	"ZREVRANK":                      false,
	"ZSCORE":                        true,
	"ZUNIONSTORE":                   true,
	"SCAN":                          false,
	"SSCAN":                         false,
	"HSCAN":                         false,
	"ZSCAN":                         false,
}